IF COL_LENGTH('dbo.CATEGORIES', 'ViewerImageMediaID_FK') IS NULL
    ALTER TABLE dbo.CATEGORIES ADD ViewerImageMediaID_FK uniqueidentifier NULL;

IF COL_LENGTH('dbo.CATEGORIES', 'ViewerIcon') IS NULL
    ALTER TABLE dbo.CATEGORIES ADD ViewerIcon nvarchar(50) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_CATEGORIES_ViewerImageMediaID_FK')
    CREATE INDEX IX_CATEGORIES_ViewerImageMediaID_FK
        ON dbo.CATEGORIES (ViewerImageMediaID_FK);

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_CATEGORIES_ViewerImage_MEDIA_FILES')
    ALTER TABLE dbo.CATEGORIES WITH CHECK ADD CONSTRAINT FK_CATEGORIES_ViewerImage_MEDIA_FILES
        FOREIGN KEY (ViewerImageMediaID_FK) REFERENCES dbo.MEDIA_FILES (MediaID) ON DELETE SET NULL;
