SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.ARTICLE_NOTIFICATION_PREFERENCES', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ARTICLE_NOTIFICATION_PREFERENCES
    (
        UserID_FK uniqueidentifier NOT NULL,
        ArticleID_FK uniqueidentifier NOT NULL,
        IsEnabled bit NOT NULL CONSTRAINT DF_ARTICLE_NOTIFICATION_PREFERENCES_IsEnabled DEFAULT (1),
        UpdatedAt datetime2(3) NOT NULL CONSTRAINT DF_ARTICLE_NOTIFICATION_PREFERENCES_UpdatedAt DEFAULT sysutcdatetime(),
        CONSTRAINT PK_ARTICLE_NOTIFICATION_PREFERENCES PRIMARY KEY (UserID_FK, ArticleID_FK),
        CONSTRAINT FK_ARTICLE_NOTIFICATION_PREFERENCES_USERS FOREIGN KEY (UserID_FK)
            REFERENCES dbo.USERS (UserID) ON DELETE CASCADE,
        CONSTRAINT FK_ARTICLE_NOTIFICATION_PREFERENCES_ARTICLES FOREIGN KEY (ArticleID_FK)
            REFERENCES dbo.ARTICLES (ArticleID) ON DELETE CASCADE
    );
END;

COMMIT TRANSACTION;
