SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.MIGRATION_EXTERNAL_MAPPINGS', N'U') IS NOT NULL
    DROP TABLE dbo.MIGRATION_EXTERNAL_MAPPINGS;

IF OBJECT_ID(N'dbo.MIGRATION_JOB_ERRORS', N'U') IS NOT NULL
    DROP TABLE dbo.MIGRATION_JOB_ERRORS;

IF OBJECT_ID(N'dbo.MIGRATION_JOBS', N'U') IS NOT NULL
    DROP TABLE dbo.MIGRATION_JOBS;

COMMIT TRANSACTION;
